build: fallible test

diff --git a/.github/workflows/development.yml b/.github/workflows/development.yml
--- a/.github/workflows/development.yml
+++ b/.github/workflows/development.yml
@@ -199,6 +199,10 @@ jobs:
             local T="$(mktemp)"
             trap 'rm -f '"$T" RETURN
             >"$T" 2>&1 eval "$@" || rv=$?
+            if [ $rv -eq 0 ] && case "$(tail -1 $T)" in '<p>Hello, World!</p>') false ;; *) true ;; esac ; then
+              >&2 echo 'failed! got "'"$(tail -1 $T)"'" !'
+              rv=1
+            fi
             printf '`%s` (returned code: ' "$@"
             printf '%s)\n```\n' "$rv"
             cat "$T"
